### ISSUE TITLE
FireStoreから読み込んだデータをrefに追加できない

### ISSUE THREAD

**Issue by azain4645** [azain4645/1phraseBbs#1]
phrasesにFirestoreから取得したデータを入れたいのですが、うまく動作しません。

// phrases.value.push = {text: 'test2', created_date: '2002'}
も動作しないので、firestoreの問題ではないかもしれません。

https://github.com/azain4645/1phraseBbs/blob/77deeb9dbee96d4b1154f5dd7ca6a8281b9c8603/pages/index.vue#L90-L105

あと、firebaseから取得したデータの型は
DocumentSnapshot<DocumentData>
となっていますが、これをこちらが扱いたい型として扱うというようなことは出来ますか？

**Comment by azain4645** [comment]
型の問題は、
```
    const doc = await getDoc(ref)
    const addDoc = <Phrase>{
      text : doc.data().text,
      created_date: doc.data().created_date
    }
    phrases.value.push = addDoc
```
こんな感じでオブジェクトかましたらいけそうな気がしましたが、考え方合っていますか？

**Comment by azain4645** [comment]
すみません、読み込んだデータをrefに反映すること自体は自己解決しました！

読み込み時のメソッドです
```
const readFromFirestore = async () => {
  try {
    const q = query(collection(db, "phrases"), orderBy('created_date', 'desc'));

    const querySnapshot = await getDocs(q);
    const Docs = <Phrase[]>([])

    querySnapshot.forEach((doc) => {
      const addDoc = <Phrase>{
        text : doc.data().text,
        created_date: doc.data().created_date
      }
      Docs.push(addDoc)
    });

    phrases.value = Docs
  } catch (e) {
    alert("Error!")
    console.error(e)
  }
}
```

**Comment by azain4645** [comment]
ただ、初期値としてデータを読み込むやり方がわかりませんので、教えてもらえますか？
しかして、DBの内容が変更されたら反映させるみたいなことも、やり方によっては可能ですか？

**Comment by azain4645** [comment]
また、
https://coinbaby8.com/firebase-ver9-nuxtjs.html
このサイトを参考に、firebaseの初期化をpuluginに外部化しましたが、pageの方で使う時にundefindとなり使えませんでした。

nuxt.configに書くやり方もみましたが、設定の方はわかっても使う側がイマイチわかりませんでした。。

**Comment by Kenpal-ShigeruHyodo** [comment]
@azain4645 
先にプラグインの方からお答えしますね！（初期値の方は明日の朝確認＆お返事差し上げます）

プラグインについてですが、見たところ参考にされてる記事がNuxt2のコードのようです！

ちょうどNuxt3でプラグインにFirebaseを設定し、フロントエンドでどう使うかまで書かれているIssueがあるので、連携しますね！これをご覧になりながら実装すればいけると思います。

方法1
https://github.com/nuxt/framework/discussions/2404#discussioncomment-1825342

方法2
https://github.com/nuxt/framework/discussions/2404#discussioncomment-1980363

参考：Nuxt3公式
https://v3.nuxtjs.org/guide/directory-structure/plugins


（もし分からなければ気軽にご質問ください！）

**Comment by gel1123** [comment]
@azain4645 
おはようございます！　昨夜お返事できなかった分を回答しますね！

> ただ、初期値としてデータを読み込むやり方がわかりませんので、教えてもらえますか？

画面を初期表示した時に、Firebaseから読み込んだデータをすぐに画面に表示させたいという意味ですよね？
でしたら、Firestoreからデータを読み込む関数は作成済みのようですし、
その読み込み関数を初期表示の時点で実行すればいいですよ！

```diff
const phrases = ref<Phrase[]>([])
+ readFromFirestore();
const message = ref('')
</script>
```

あるいは、マウント後に読み込むならこうですね！

```diff
const phrases = ref<Phrase[]>([])
+ onMounted(() => {
+   readFromFirestore()
+ })
const message = ref('')
</script>
```

※マウントとは何か、がもし分からなければ下記で説明と使い方があるのでご覧ください！
* https://v3.ja.vuejs.org/api/options-lifecycle-hooks.html#created
* https://v3.ja.vuejs.org/guide/composition-api-lifecycle-hooks.html

------------

> しかして、DBの内容が変更されたら反映させるみたいなことも、やり方によっては可能ですか？

はい、Firestoreの Realtime listeners という機能で実現可能です！
公式ドキュメントに詳しく解説があるので、下記にリンク記載しますね！

https://firebase.google.com/docs/firestore/query-data/listen

**Comment by azain4645** [comment]
ありがとうございます！
とりあえず、Firebase接続のplugin化と、onMountedで読み込むようにできました！
リアルタイムの反映はまた、機会があればやってみます
